In [1]:
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv'
df = pd.read_csv(url)
df.to_csv('data/00.raw/state.csv', index=False)

In [4]:
df[df.location=="Alabama"]

,date,location,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used
0,2021-01-12,Alabama,78134.0,377025.0,70861.0,0.15,1.59,7270.0,1.45,7.69,NaN,NaN,NaN,0.207
1,2021-01-13,Alabama,84040.0,378975.0,74792.0,0.19,1.71,9245.0,1.53,7.73,5906.0,5906.0,1205.0,0.222
2,2021-01-14,Alabama,92300.0,435350.0,80480.0,NaN,1.88,NaN,1.64,8.88,8260.0,7083.0,1445.0,0.212
3,2021-01-15,Alabama,100567.0,444650.0,86956.0,0.28,2.05,13488.0,1.77,9.07,8267.0,7478.0,1525.0,0.226
4,2021-01-16,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7557.0,7498.0,1529.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2021-07-06,Alabama,3392366.0,4845190.0,1976343.0,32.99,69.19,1617584.0,40.31,98.82,5162.0,6066.0,1237.0,0.700
176,2021-07-07,Alabama,3396338.0,4845190.0,1978951.0,33.03,69.27,1619647.0,40.36,98.82,3972.0,6533.0,1332.0,0.701
177,2021-07-08,Alabama,3402487.0,4866130.0,1982250.0,33.10,69.39,1623114.0,40.43,99.24,6149.0,5299.0,1081.0,0.699
178,2021-07-09,Alabama,3408591.0,4872940.0,1985582.0,33.17,69.52,1626323.0,40.50,99.38,6104.0,6138.0,1252.0,0.699
179,2021-07-10,Alabama,3414916.0,4884130.0,1988956.0,33.24,69.65,1629745.0,40.56,99.61,6325.0,4703.0,959.0,0.699

In [5]:
df['date'] = pd.to_datetime(df['date'])

In [6]:
oldest_date = df.date.min()
most_recent = df.date.max()

print(f'The first date in the df is {oldest_date} and the most recent is {most_recent}.')

The first date in the df is 2020-12-20 00:00:00 and the most recent is 2021-07-10 00:00:00.

In [7]:
df_sorted = (df.sort_values('date')
               .groupby('location')
               .tail(1)
               .sort_values('location')
    )

In [8]:
df_sorted.count()

date                                   65
location                               65
total_vaccinations                     65
total_distributed                      64
people_vaccinated                      64
people_fully_vaccinated_per_hundred    61
total_vaccinations_per_hundred         61
people_fully_vaccinated                64
people_vaccinated_per_hundred          61
distributed_per_hundred                61
daily_vaccinations_raw                 65
daily_vaccinations                     65
daily_vaccinations_per_million         61
share_doses_used                       64
dtype: int64

In [9]:
state_names = ["Alaska", "Alabama", "Arkansas", "Arizona", "California", 
               "Colorado", "Connecticut", "District of Columbia", "Delaware", 
               "Florida", "Georgia", "Hawaii", "Iowa", "Idaho", "Illinois", 
               "Indiana", "Kansas", "Kentucky", "Louisiana", "Massachusetts", 
               "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", 
               "Montana", "North Carolina", "North Dakota", "Nebraska", "New Hampshire", 
               "New Jersey", "New Mexico", "Nevada", "New York", "Ohio", "Oklahoma",
               "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
               "Tennessee", "Texas", "Utah", "Virginia", "Vermont", "Washington", 
               "Wisconsin", "West Virginia", "Wyoming"]

state_names.sort()

state_abbr = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", 
              "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", 
              "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", 
              "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", 
              "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", 
              "WY"]

state_dict = dict(zip(state_names, state_abbr))

# thisdict["year"] = 2018

state_dict["Delaware"] = "DE"
state_dict["District of Columbia"] = "DC"


list(state_dict.items())[:5]

[('Alabama', 'AL'),
 ('Alaska', 'AK'),
 ('Arizona', 'AZ'),
 ('Arkansas', 'AR'),
 ('California', 'CA')]

In [10]:
df_filtered = df_sorted[df_sorted.location.isin(state_names)]
df_filtered.count()

date                                   50
location                               50
total_vaccinations                     50
total_distributed                      50
people_vaccinated                      50
people_fully_vaccinated_per_hundred    50
total_vaccinations_per_hundred         50
people_fully_vaccinated                50
people_vaccinated_per_hundred          50
distributed_per_hundred                50
daily_vaccinations_raw                 50
daily_vaccinations                     50
daily_vaccinations_per_million         50
share_doses_used                       50
dtype: int64

In [11]:
df_filtered.sort_values('people_fully_vaccinated_per_hundred', ascending=False).head()

,date,location,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used
10462,2021-07-10,Vermont,859026.0,931580.0,464492.0,66.32,137.67,413833.0,74.44,149.29,906.0,658.0,1055.0,0.922
5399,2021-07-10,Massachusetts,8945400.0,9829100.0,4900571.0,62.51,129.78,4308593.0,71.10,142.61,10192.0,8685.0,1260.0,0.910
4859,2021-07-10,Maine,1633699.0,1874270.0,901386.0,62.40,121.54,838767.0,67.06,139.43,2049.0,1527.0,1136.0,0.872
1619,2021-07-10,Connecticut,4466279.0,4783225.0,2418107.0,61.61,125.27,2196584.0,67.82,134.16,6542.0,6230.0,1747.0,0.934
9179,2021-07-10,Rhode Island,1293080.0,1528665.0,691950.0,59.80,122.06,633445.0,65.32,144.30,1846.0,1583.0,1494.0,0.846

In [12]:
df_filtered.loc[:, 'state'] = df_filtered.loc[:, 'location'].map(state_dict)

/home/evan/anaconda3/envs/tutorials/lib/python3.6/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/home/evan/anaconda3/envs/tutorials/lib/python3.6/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

In [13]:
df_filtered.head()

,date,location,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used,state
179,2021-07-10,Alabama,3414916.0,4884130.0,1988956.0,33.24,69.65,1629745.0,40.56,99.61,6325.0,4703.0,959.0,0.699,AL
359,2021-07-10,Alaska,681805.0,840265.0,368156.0,44.44,93.20,325118.0,50.33,114.86,1266.0,1874.0,2562.0,0.811,AK
719,2021-07-10,Arizona,6870625.0,8243660.0,3728161.0,43.91,94.39,3196388.0,51.22,113.26,13804.0,10797.0,1483.0,0.833,AZ
899,2021-07-10,Arkansas,2280113.0,2877040.0,1292845.0,34.83,75.56,1051172.0,42.84,95.34,5305.0,3951.0,1309.0,0.793,AR
1259,2021-07-10,California,43507479.0,49668485.0,24679946.0,50.93,110.11,20124209.0,62.46,125.70,74111.0,75909.0,1921.0,0.876,CA

In [14]:
df_filtered.tail(10)

,date,location,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used,state
9539,2021-07-10,South Dakota,829025.0,972075.0,452059.0,45.97,93.71,406710.0,51.10,109.88,1152.0,836.0,945.0,0.853,SD
9719,2021-07-10,Tennessee,5530977.0,6431980.0,2926141.0,37.92,80.99,2589941.0,42.85,94.18,11295.0,7780.0,1139.0,0.860,TN
9899,2021-07-10,Texas,26195987.0,32252315.0,14215759.0,42.09,90.34,12205276.0,49.03,111.23,65847.0,45353.0,1564.0,0.812,TX
10282,2021-07-10,Utah,2896443.0,3276200.0,1587256.0,38.08,90.35,1220762.0,49.51,102.19,6166.0,5604.0,1748.0,0.884,UT
10462,2021-07-10,Vermont,859026.0,931580.0,464492.0,66.32,137.67,413833.0,74.44,149.29,906.0,658.0,1055.0,0.922,VT
11002,2021-07-10,Virginia,9380725.0,10503275.0,5107865.0,52.82,109.90,4508239.0,59.84,123.05,14369.0,12735.0,1492.0,0.893,VA
11182,2021-07-10,Washington,8749728.0,9520555.0,4741874.0,55.81,114.90,4250081.0,62.27,125.03,15526.0,17527.0,2302.0,0.919,WA
11362,2021-07-10,West Virginia,1478219.0,1917265.0,817861.0,38.68,82.48,693240.0,45.64,106.98,631.0,7421.0,4141.0,0.771,WV
11542,2021-07-10,Wisconsin,6008927.0,6207245.0,3159176.0,50.59,103.20,2945809.0,54.26,106.61,8522.0,8407.0,1444.0,0.968,WI
11722,2021-07-10,Wyoming,434799.0,519885.0,233010.0,35.69,75.13,206571.0,40.26,89.83,780.0,542.0,936.0,0.836,WY

In [15]:
df_filtered.to_csv('data/01.transformed/states.csv', index=False)
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50 entries, 179 to 11722
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   date                                 50 non-null     datetime64[ns]
 1   location                             50 non-null     object
 2   total_vaccinations                   50 non-null     float64
 3   total_distributed                    50 non-null     float64
 4   people_vaccinated                    50 non-null     float64
 5   people_fully_vaccinated_per_hundred  50 non-null     float64
 6   total_vaccinations_per_hundred       50 non-null     float64
 7   people_fully_vaccinated              50 non-null     float64
 8   people_vaccinated_per_hundred        50 non-null     float64
 9   distributed_per_hundred              50 non-null     float64
 10  daily_vaccinations_raw               50 non-null     float64
 11  daily_vaccinations                   50 non-null     float64
 12  daily_vaccinations_per_million       50 non-null     float64
 13  share_doses_used                     50 non-null     float64
 14  state                                50 non-null     object
dtypes: datetime64[ns](1), float64(12), object(2)
memory usage: 6.2+ KB

In [20]:
store = pd.read_csv('data/00.raw/store_info.csv')
store.head()

,store_name,street,city,state,zip,landline,mobile,website
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,408-736-7573,408-736-7573,https://locations.traderjoes.com/ca/sunnyvale/68/
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,949-643-5531,949-643-5531,https://locations.traderjoes.com/ca/aliso-viej...
2,Trader Joe's Brookline (501),1317 Beacon St,Brookline,MA,02446,617-278-9997,617-278-9997,https://locations.traderjoes.com/ma/brookline/...
3,Trader Joe's Park Ridge (698),190 N NW Highway,Park Ridge,IL,60068,847-292-1108,847-292-1108,https://locations.traderjoes.com/il/park-ridge...
4,Trader Joe's Scottsdale (94),6202 N Scottsdale Rd,Scottsdale,AZ,85253,480-948-9886,480-948-9886,https://locations.traderjoes.com/az/scottsdale...

In [21]:
keep = ['date', "state", 'location', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred']

df_filtered = df_filtered.loc[:, keep]

df_merge = pd.merge(store, df_filtered, on='state')

In [22]:
df_merge.head()

,store_name,street,city,state,zip,landline,mobile,website,date,location,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,408-736-7573,408-736-7573,https://locations.traderjoes.com/ca/sunnyvale/68/,2021-07-10,California,62.46,50.93
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,949-643-5531,949-643-5531,https://locations.traderjoes.com/ca/aliso-viej...,2021-07-10,California,62.46,50.93
2,Trader Joe's Newport Beach (125),8086 E Pacific Coast Hwy,Newport Beach,CA,92657,949-494-7404,949-494-7404,https://locations.traderjoes.com/ca/newport-be...,2021-07-10,California,62.46,50.93
3,Trader Joe's Pleasanton (66),3903 Santa Rita Road,Pleasanton,CA,94588,925-468-0763,925-468-0763,https://locations.traderjoes.com/ca/pleasanton...,2021-07-10,California,62.46,50.93
4,Trader Joe's Costa Mesa (35),640 W 17th St,Costa Mesa,CA,92627,949-642-5134,949-642-5134,https://locations.traderjoes.com/ca/costa-mesa...,2021-07-10,California,62.46,50.93

In [23]:
df_merge.to_csv('data/01.transformed/store_covid.csv', index=False)