In [1]:
import pandas as pd

In [2]:
path = "data/00.raw/cleaned_vaccine_0708.csv"

df = pd.read_csv(path, 
                 dtype={'zip_code':object},
                  parse_dates=['start_date', 'end_date'])
df.head()

,week,start_date,end_date,zip_code,vaccine_measure_id,final_zip_pred,state_name,county_name,vaccine_measure_name,definition
0,26,2021-06-25,2021-07-01,10001,1,0.043939,New York,New York County,high_vaccine_potential,yes probably will and no probably wont respond...
1,26,2021-06-25,2021-07-01,10002,1,0.062324,New York,New York County,high_vaccine_potential,yes probably will and no probably wont respond...
2,26,2021-06-25,2021-07-01,10003,1,0.024404,New York,New York County,high_vaccine_potential,yes probably will and no probably wont respond...
3,26,2021-06-25,2021-07-01,10004,1,0.036839,New York,New York County,high_vaccine_potential,yes probably will and no probably wont respond...
4,26,2021-06-25,2021-07-01,10005,1,0.036940,New York,New York County,high_vaccine_potential,yes probably will and no probably wont respond...

In [3]:
df.sort_values(by='final_zip_pred')

,week,start_date,end_date,zip_code,vaccine_measure_id,final_zip_pred,state_name,county_name,vaccine_measure_name,definition
43983,26,2021-06-25,2021-07-01,99606,1,0.000122,Alaska,Lake and Peninsula Borough,high_vaccine_potential,yes probably will and no probably wont respond...
38898,26,2021-06-25,2021-07-01,83423,1,0.000185,Idaho,Clark County,high_vaccine_potential,yes probably will and no probably wont respond...
44021,26,2021-06-25,2021-07-01,99653,1,0.000213,Alaska,Lake and Peninsula Borough,high_vaccine_potential,yes probably will and no probably wont respond...
26196,26,2021-06-25,2021-07-01,59087,1,0.000285,Montana,Petroleum County,high_vaccine_potential,yes probably will and no probably wont respond...
25250,26,2021-06-25,2021-07-01,57540,1,0.000288,South Dakota,Hyde County,high_vaccine_potential,yes probably will and no probably wont respond...
...,...,...,...,...,...,...,...,...,...,...
69507,26,2021-06-25,2021-07-01,57644,2,0.949979,South Dakota,Ziebach County,all_vaccine_potential,"yes probably will, no probably wont, and no de..."
69506,26,2021-06-25,2021-07-01,57644,2,0.949979,South Dakota,Perkins County,all_vaccine_potential,"yes probably will, no probably wont, and no de..."
69505,26,2021-06-25,2021-07-01,57644,2,0.949979,South Dakota,Corson County,all_vaccine_potential,"yes probably will, no probably wont, and no de..."
69697,26,2021-06-25,2021-07-01,58062,2,0.952697,North Dakota,Ransom County,all_vaccine_potential,"yes probably will, no probably wont, and no de..."
69696,26,2021-06-25,2021-07-01,58062,2,0.952697,North Dakota,Barnes County,all_vaccine_potential,"yes probably will, no probably wont, and no de..."

In [4]:
df.zip_code.str.len().unique()

array([5])

In [5]:
df[df.vaccine_measure_id == 2].shape

(44174, 10)

In [6]:
df_all_vaccine = df[df.vaccine_measure_id == 2].drop_duplicates(subset='zip_code', keep='first')

In [7]:
df_all_vaccine[df_all_vaccine.zip_code.duplicated()]

Empty DataFrame
Columns: [week, start_date, end_date, zip_code, vaccine_measure_id, final_zip_pred, state_name, county_name, vaccine_measure_name, definition]
Index: []

In [8]:
store = pd.read_csv('data/00.raw/store_info.csv')
store.head()

,store_name,street,city,state,zip,landline,mobile,website
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,408-736-7573,408-736-7573,https://locations.traderjoes.com/ca/sunnyvale/68/
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,949-643-5531,949-643-5531,https://locations.traderjoes.com/ca/aliso-viej...
2,Trader Joe's Brookline (501),1317 Beacon St,Brookline,MA,02446,617-278-9997,617-278-9997,https://locations.traderjoes.com/ma/brookline/...
3,Trader Joe's Park Ridge (698),190 N NW Highway,Park Ridge,IL,60068,847-292-1108,847-292-1108,https://locations.traderjoes.com/il/park-ridge...
4,Trader Joe's Scottsdale (94),6202 N Scottsdale Rd,Scottsdale,AZ,85253,480-948-9886,480-948-9886,https://locations.traderjoes.com/az/scottsdale...

In [9]:
store.at[159, 'zip'] = '90089'
store.at[386, 'zip'] = '33156'
store.at[522, 'zip'] = '75205'


store[store.city.str.contains('Dallas')]

,store_name,street,city,state,zip,landline,mobile,website
66,Trader Joe's Dallas North (401),7939 Walnut Hill Lane,Dallas,TX,75230,214-346-6579,214-346-6579,https://locations.traderjoes.com/tx/dallas/401/
255,Trader Joe's Dallas West (405),5550 W Lovers Lane,Dallas,TX,75209,214-366-0205,214-366-0205,https://locations.traderjoes.com/tx/dallas/405/
316,Trader Joe's Dallas Far North (407),14856 Preston Rd,Dallas,TX,75254,972-239-3901,972-239-3901,https://locations.traderjoes.com/tx/dallas/407/
495,Trader Joe's Dallas - Lower Greenville (403),2001 Greenville Ave,Dallas,TX,75206,469-334-0614,469-334-0614,https://locations.traderjoes.com/tx/dallas/403/
522,Trader Joe's Dallas Knox (400),4525 Cole Ave,Dallas,TX,75205,214-599-2155,214-599-2155,https://locations.traderjoes.com/tx/dallas/400/

In [10]:
store.zip.str.len().unique()

array([5])

In [11]:
keep = ['zip_code', 'final_zip_pred']

df_merge = pd.merge(store, df_all_vaccine.loc[:, keep], how='left', left_on='zip', right_on='zip_code')

In [12]:
df_merge

,store_name,street,city,state,zip,landline,mobile,website,zip_code,final_zip_pred
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,408-736-7573,408-736-7573,https://locations.traderjoes.com/ca/sunnyvale/68/,94087,0.047050
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,949-643-5531,949-643-5531,https://locations.traderjoes.com/ca/aliso-viej...,92656,0.069219
2,Trader Joe's Brookline (501),1317 Beacon St,Brookline,MA,02446,617-278-9997,617-278-9997,https://locations.traderjoes.com/ma/brookline/...,02446,0.032207
3,Trader Joe's Park Ridge (698),190 N NW Highway,Park Ridge,IL,60068,847-292-1108,847-292-1108,https://locations.traderjoes.com/il/park-ridge...,60068,0.070867
4,Trader Joe's Scottsdale (94),6202 N Scottsdale Rd,Scottsdale,AZ,85253,480-948-9886,480-948-9886,https://locations.traderjoes.com/az/scottsdale...,85253,0.148078
...,...,...,...,...,...,...,...,...,...,...
519,Trader Joe's Arlington - Clarendon (640),1109 N Highland St,Arlington,VA,22201,703-351-8015,703-351-8015,https://locations.traderjoes.com/va/arlington/...,22201,0.030114
520,Trader Joe's Florham Park (604),176 Columbia Turnpike,Florham Park,NJ,07932,973-377-0679,973-377-0679,https://locations.traderjoes.com/nj/florham-pa...,07932,0.062207
521,Trader Joe's Olympic Blvd (215),11755 Olympic Blvd,Los Angeles,CA,90064,310-477-5949,310-477-5949,https://locations.traderjoes.com/ca/los-angele...,90064,0.045785
522,Trader Joe's Dallas Knox (400),4525 Cole Ave,Dallas,TX,75205,214-599-2155,214-599-2155,https://locations.traderjoes.com/tx/dallas/400/,75205,0.089245
523,Trader Joe's Towson (649),800 Kenilworth Drive,Towson,MD,21204,410-321-0276,410-321-0276,https://locations.traderjoes.com/md/towson/649/,21204,0.048611

In [13]:
df_merge.sort_values(by='final_zip_pred')

,store_name,street,city,state,zip,landline,mobile,website,zip_code,final_zip_pred
159,Trader Joe's USC Village (250),3131 S Hoover Street,Los Angeles,CA,90089,213-749-1497,213-749-1497,https://locations.traderjoes.com/ca/los-angele...,90089,0.010923
38,Trader Joe's Bethesda (645),6831 Wisconsin Ave,Bethesda,MD,20815,301-907-0982,301-907-0982,https://locations.traderjoes.com/md/bethesda/645/,20815,0.015659
416,Trader Joe's Oakland - Rockridge (231),5727 College Ave,Oakland,CA,94618,510-923-9428,510-923-9428,https://locations.traderjoes.com/ca/oakland/231/,94618,0.018652
47,Trader Joe's Needham Heights (504),958 Highland Ave,Needham,MA,02494,781-449-6993,781-449-6993,https://locations.traderjoes.com/ma/needham/504/,02494,0.022209
44,Trader Joe's Arlington (505),1427 Massachusetts Ave,Arlington,MA,02476,781-646-9138,781-646-9138,https://locations.traderjoes.com/ma/arlington/...,02476,0.024941
...,...,...,...,...,...,...,...,...,...,...
379,Trader Joe's Mesa (89),2050 E Baseline Rd,Mesa,AZ,85204,480-632-0951,480-632-0951,https://locations.traderjoes.com/az/mesa/89/,85204,0.288625
230,Trader Joe's Redding (219),845 Browning St,Redding,CA,96003,530-223-4875,530-223-4875,https://locations.traderjoes.com/ca/redding/219/,96003,0.290238
401,Trader Joe's Warwick (518),1000 Bald Hill Rd,Warwick,RI,02886,401-821-5368,401-821-5368,https://locations.traderjoes.com/ri/warwick/518/,02886,0.296059
147,Trader Joe's Medford (155),55 Rossanley Dr,Medford,OR,97501,541-608-4993,541-608-4993,https://locations.traderjoes.com/or/medford/155/,97501,0.297541
8,Trader Joe's Queen Creek (286),21186 S. Ellsworth Loop Rd,Queen Creek,AZ,85142,480-877-7213,480-877-7213,https://locations.traderjoes.com/az/queen-cree...,85142,0.341007

In [14]:
drop = ['landline', 'mobile', 'website', 'zip_code']

df_merge.drop(columns=drop).to_csv("data/01.transformed/store_covid_hesitancy.csv", index=False)