In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/BroadbandNow/Open-Data/master/broadband_data_opendatachallenge.csv'
df = pd.read_csv(url, encoding='latin-1', dtype={'Zip': object})
df.to_csv('data/00.raw/internet.csv', index=False)

# https://github.com/BroadbandNow/Open-Data

In [3]:
df.head()

,Zip,Population,County,State,WiredCount_2020,Fwcount_2020,AllProviderCount_2020,Wired25_3_2020,Wired100_3_2020,All25_3_2020,...,FastestAverageMbps,%Access to Terrestrial Broadband,Lowest Priced Terrestrial Broadband Plan,WiredCount_2015,Fwcount_2015,AllProviderCount_2015,Wired25_3_2015,Wired100_3_2015,All25_3_2015,All100_3.1
0,29620,12934.0,Abbeville,South Carolina,6.0,0.0,11.0,5.0,3.0,7.0,...,536.35,98%,40.00,6.0,0.0,8.0,3.0,3.0,3.0,3.0
1,29628,2759.0,Abbeville,South Carolina,4.0,0.0,8.0,3.0,2.0,5.0,...,126.06,95%,40.00,4.0,0.0,6.0,3.0,3.0,3.0,3.0
2,29638,2944.0,Abbeville,South Carolina,6.0,1.0,13.0,4.0,4.0,6.0,...,222.35,95%,40.00,5.0,0.0,7.0,2.0,2.0,2.0,2.0
3,29639,1742.0,Abbeville,South Carolina,3.0,0.0,8.0,3.0,3.0,5.0,...,223.75,90%,40.00,3.0,0.0,5.0,3.0,3.0,3.0,3.0
4,70516,1546.0,Acadia,Louisiana,4.0,3.0,12.0,2.0,2.0,4.0,...,9.41,33%,69.99,4.0,2.0,8.0,2.0,1.0,2.0,1.0

In [4]:
df.count()

Zip                                         32608
Population                                  29727
County                                      32608
State                                       32608
WiredCount_2020                             29733
Fwcount_2020                                29733
AllProviderCount_2020                       29733
Wired25_3_2020                              29733
Wired100_3_2020                             29733
All25_3_2020                                29733
All100_3                                    29733
TestCount                                   26368
AverageMbps                                 26368
FastestAverageMbps                          26368
%Access to Terrestrial Broadband            29685
Lowest Priced Terrestrial Broadband Plan    26630
WiredCount_2015                             29730
Fwcount_2015                                29730
AllProviderCount_2015                       29730
Wired25_3_2015                              29730
Wired100_3_2015                             29730
All25_3_2015                                29730
All100_3.1                                  29730
dtype: int64

In [5]:
df.loc[:, ['Zip', 'AverageMbps', 'FastestAverageMbps']].sort_values(by="Zip")

         Zip  AverageMbps  FastestAverageMbps
21003  10001       135.49              320.82
21004  10002       130.18              251.70
21005  10003      2289.33             6802.47
21006  10004        56.17              165.91
21007  10005       140.07              388.14
...      ...          ...                 ...
32552  99926         4.57                9.25
32553  99927          NaN                 NaN
32478  99928          NaN                 NaN
32577  99929        27.59               84.59
32479  99950          NaN                 NaN

[32608 rows x 3 columns]

In [6]:
df[df.Zip.str.endswith("0")]

,Zip,Population,County,State,WiredCount_2020,Fwcount_2020,AllProviderCount_2020,Wired25_3_2020,Wired100_3_2020,All25_3_2020,...,FastestAverageMbps,%Access to Terrestrial Broadband,Lowest Priced Terrestrial Broadband Plan,WiredCount_2015,Fwcount_2015,AllProviderCount_2015,Wired25_3_2015,Wired100_3_2015,All25_3_2015,All100_3.1
0,29620,12934.0,Abbeville,South Carolina,6.0,0.0,11.0,5.0,3.0,7.0,...,536.35,98%,40.00,6.0,0.0,8.0,3.0,3.0,3.0,3.0
33,23410,2015.0,Accomack,Virginia,3.0,2.0,10.0,1.0,1.0,4.0,...,5.17,63%,59.99,2.0,1.0,5.0,1.0,1.0,1.0,1.0
37,23420,2376.0,Accomack,Virginia,3.0,3.0,11.0,1.0,1.0,4.0,...,4.41,40%,59.99,2.0,1.0,5.0,1.0,1.0,1.0,1.0
40,83720,NaN,Ada,Idaho,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,83730,NaN,Ada,Idaho,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32575,99650,568.0,Wade Hampton,Alaska,0.0,2.0,3.0,0.0,0.0,0.0,...,1.59,0,NaN,0.0,2.0,3.0,0.0,0.0,0.0,0.0
32584,99720,208.0,Yukon-Koyukuk,Alaska,0.0,0.0,1.0,0.0,0.0,0.0,...,NaN,0,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0
32587,99730,144.0,Yukon-Koyukuk,Alaska,0.0,1.0,2.0,0.0,0.0,0.0,...,NaN,0,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0
32588,99740,585.0,Yukon-Koyukuk,Alaska,2.0,1.0,4.0,0.0,0.0,0.0,...,31.71,0,NaN,1.0,1.0,3.0,0.0,0.0,0.0,0.0
32593,99590,194.0,Yukon-Koyukuk,Alaska,1.0,1.0,3.0,0.0,0.0,0.0,...,1.37,0,NaN,1.0,1.0,3.0,0.0,0.0,0.0,0.0

In [7]:
df[df.Zip.str.startswith("0")]

Empty DataFrame
Columns: [Zip, Population, County, State, WiredCount_2020, Fwcount_2020, AllProviderCount_2020, Wired25_3_2020, Wired100_3_2020, All25_3_2020, All100_3, TestCount, AverageMbps, FastestAverageMbps, %Access to Terrestrial Broadband, Lowest Priced Terrestrial Broadband Plan, WiredCount_2015, Fwcount_2015, AllProviderCount_2015, Wired25_3_2015, Wired100_3_2015, All25_3_2015, All100_3.1]
Index: []

[0 rows x 23 columns]

In [8]:
df.Zip = df.Zip.str.rjust(5, '0')

In [9]:
df[df.Zip.str.startswith("0")]

,Zip,Population,County,State,WiredCount_2020,Fwcount_2020,AllProviderCount_2020,Wired25_3_2020,Wired100_3_2020,All25_3_2020,...,FastestAverageMbps,%Access to Terrestrial Broadband,Lowest Priced Terrestrial Broadband Plan,WiredCount_2015,Fwcount_2015,AllProviderCount_2015,Wired25_3_2015,Wired100_3_2015,All25_3_2015,All100_3.1
174,05456,1277.0,Addison,Vermont,4.0,2.0,12.0,4.0,2.0,6.0,...,NaN,97%,53.95,10.0,1.0,13.0,3.0,2.0,3.0,2.0
175,05747,280.0,Addison,Vermont,2.0,3.0,9.0,2.0,1.0,4.0,...,NaN,95%,72.00,3.0,1.0,6.0,0.0,0.0,0.0,0.0
176,05748,323.0,Addison,Vermont,2.0,2.0,9.0,1.0,1.0,3.0,...,NaN,96%,72.00,5.0,2.0,9.0,0.0,0.0,0.0,0.0
177,05760,1123.0,Addison,Vermont,1.0,3.0,8.0,0.0,0.0,3.0,...,NaN,39%,54.90,2.0,2.0,6.0,1.0,1.0,1.0,1.0
178,05443,6656.0,Addison,Vermont,5.0,3.0,13.0,4.0,3.0,6.0,...,28.26,97%,53.95,4.0,2.0,8.0,3.0,2.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32287,04083,4525.0,York,Maine,4.0,1.0,10.0,3.0,3.0,6.0,...,163.17,99%,39.99,6.0,1.0,8.0,3.0,1.0,3.0,1.0
32288,04087,2116.0,York,Maine,2.0,0.0,8.0,1.0,1.0,3.0,...,438.27,100%,69.99,4.0,0.0,5.0,1.0,0.0,1.0,0.0
32289,04090,9589.0,York,Maine,5.0,0.0,10.0,5.0,4.0,7.0,...,112.15,100%,48.79,4.0,0.0,5.0,1.0,0.0,1.0,0.0
32290,04093,8034.0,York,Maine,3.0,0.0,9.0,2.0,1.0,4.0,...,113.84,100%,69.99,3.0,0.0,4.0,1.0,0.0,1.0,0.0
32291,04095,1274.0,York,Maine,4.0,0.0,8.0,4.0,2.0,6.0,...,0.96,93%,39.99,4.0,1.0,6.0,2.0,0.0,2.0,0.0

In [10]:
df.to_csv('data/01.transformed/internet.csv', index=False)

In [11]:
df2 = pd.read_csv('data/01.transformed/internet.csv', dtype={'Zip': object})
df2[df2.Zip.str.startswith('0')].count()

Zip                                         2565
Population                                  2361
County                                      2565
State                                       2565
WiredCount_2020                             2363
Fwcount_2020                                2363
AllProviderCount_2020                       2363
Wired25_3_2020                              2363
Wired100_3_2020                             2363
All25_3_2020                                2363
All100_3                                    2363
TestCount                                   2241
AverageMbps                                 2241
FastestAverageMbps                          2241
%Access to Terrestrial Broadband            2353
Lowest Priced Terrestrial Broadband Plan    2273
WiredCount_2015                             2362
Fwcount_2015                                2362
AllProviderCount_2015                       2362
Wired25_3_2015                              2362
Wired100_3_2015                             2362
All25_3_2015                                2362
All100_3.1                                  2362
dtype: int64

In [12]:
store = pd.read_csv('data/01.transformed/store_covid_hesitancy.csv', dtype={"zip": object})
store.head()

,store_name,street,city,state,zip,final_zip_pred
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,0.047050
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,0.069219
2,Trader Joe's Brookline (501),1317 Beacon St,Brookline,MA,02446,0.032207
3,Trader Joe's Park Ridge (698),190 N NW Highway,Park Ridge,IL,60068,0.070867
4,Trader Joe's Scottsdale (94),6202 N Scottsdale Rd,Scottsdale,AZ,85253,0.148078

In [13]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   store_name      524 non-null    object
 1   street          524 non-null    object
 2   city            524 non-null    object
 3   state           524 non-null    object
 4   zip             524 non-null    object
 5   final_zip_pred  524 non-null    float64
dtypes: float64(1), object(5)
memory usage: 24.7+ KB

In [14]:
store[store.zip.str.startswith('0')].count()

store_name        53
street            53
city              53
state             53
zip               53
final_zip_pred    53
dtype: int64

In [15]:
store[store.zip.str.endswith('0')].count()

store_name        62
street            62
city              62
state             62
zip               62
final_zip_pred    62
dtype: int64

In [16]:
store.query("zip.str.startswith('0') and zip.str.endswith('0')")

,store_name,street,city,state,zip,final_zip_pred
54,Trader Joe's Darien (522),436 Boston Post Rd,Darien,CT,06820,0.051652
59,Trader Joe's Nashua (507),262 Daniel Webster HWY,Nashua,NH,03060,0.157446
75,Trader Joe's Princeton (607),3528 Brunswick Pike,Princeton,NJ,08540,0.033182
79,Trader Joe's Wayne (603),910 Hamburg Turnpike,Wayne,NJ,07470,0.076113
114,Trader Joe's Peabody (516),300 Andover St,Peabody,MA,01960,0.140138
119,Trader Joe's Acton (511),145 Great Rd,Acton,MA,01720,0.026176
130,Trader Joe's Westfield (601),155 Elm St,Westfield,NJ,07090,0.079045
227,Trader Joe's Fort Point Seaport (566),44 Thomson Place,Boston,MA,02210,0.063651
317,Trader Joe's Hoboken (611),1350 Willow Ave.,Hoboken,NJ,07030,0.050021
324,Trader Joe's Westport (521),400 Post Road E,Westport,CT,06880,0.031969
385,Trader Joe's Bedford (562),2 Market Street,Bedford,NH,03110,0.088392
414,Trader Joe's Edgewater (606),715 River Rd,Edgewater,NJ,07020,0.064639
506,Trader Joe's West Hartford (526),1489 New Britain Ave,West Hartford,CT,06110,0.093551

In [17]:
keep = ['Population', 'Zip', 'County', 'AverageMbps', 'FastestAverageMbps']

df = df.loc[:, keep]

df_merge = pd.merge(store, df, left_on='zip', right_on="Zip")

In [18]:
df_merge.head()

,store_name,street,city,state,zip,final_zip_pred,Population,Zip,County,AverageMbps,FastestAverageMbps
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,0.047050,54293.0,94087,Santa Clara,101.59,243.35
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,0.069219,49046.0,92656,Orange,116.61,297.85
2,Trader Joe's Brookline (501),1317 Beacon St,Brookline,MA,02446,0.032207,29311.0,02446,Norfolk,113.27,268.97
3,Trader Joe's Park Ridge (698),190 N NW Highway,Park Ridge,IL,60068,0.070867,37475.0,60068,Cook,147.68,295.55
4,Trader Joe's Scottsdale (94),6202 N Scottsdale Rd,Scottsdale,AZ,85253,0.148078,17047.0,85253,Maricopa,156.16,336.65

In [19]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 524 entries, 0 to 523
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   store_name          524 non-null    object
 1   street              524 non-null    object
 2   city                524 non-null    object
 3   state               524 non-null    object
 4   zip                 524 non-null    object
 5   final_zip_pred      524 non-null    float64
 6   Population          524 non-null    float64
 7   Zip                 524 non-null    object
 8   County              524 non-null    object
 9   AverageMbps         524 non-null    float64
 10  FastestAverageMbps  524 non-null    float64
dtypes: float64(4), object(7)
memory usage: 49.1+ KB

In [20]:
df_merge.to_csv('data/01.transformed/store_covid_hesitancy_internet.csv', index=False)