In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/01.transformed/store_covid_hesitancy_internet.csv', dtype={'zip':object, 'Zip':object})
print(df.shape)
df.head()

(524, 11)

,store_name,street,city,state,zip,final_zip_pred,Population,Zip,County,AverageMbps,FastestAverageMbps
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,0.047050,54293.0,94087,Santa Clara,101.59,243.35
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,0.069219,49046.0,92656,Orange,116.61,297.85
2,Trader Joe's Brookline (501),1317 Beacon St,Brookline,MA,02446,0.032207,29311.0,02446,Norfolk,113.27,268.97
3,Trader Joe's Park Ridge (698),190 N NW Highway,Park Ridge,IL,60068,0.070867,37475.0,60068,Cook,147.68,295.55
4,Trader Joe's Scottsdale (94),6202 N Scottsdale Rd,Scottsdale,AZ,85253,0.148078,17047.0,85253,Maricopa,156.16,336.65

In [3]:
df.columns

Index(['store_name', 'street', 'city', 'state', 'zip', 'final_zip_pred',
       'Population', 'Zip', 'County', 'AverageMbps', 'FastestAverageMbps'],
      dtype='object')

In [4]:
transit = pd.read_csv('data/01.transformed/transit.csv')
transit.head()

,place,name,blkgrps,population,households,alltransit_performance_score,state
0,1600100,Aberdeen,1.03,1364.42,426.26,0.0,ID
1,1600280,Acequia,0.01,17.81,6.47,0.0,ID
2,1601000,Albion,0.00,1.45,0.48,0.0,ID
3,1601900,American Falls,1.71,2393.44,779.77,0.0,ID
4,1601990,Ammon,3.64,11207.42,3730.59,0.9,ID

In [5]:
transit.at[20, 'name'] = "Boise"

In [6]:
transit.at[28133, 'name'] = "Athens"
transit.at[2619, 'name'] = "Nashville"
transit.at[9786, 'name'] = "Ventura"
transit.at[8589, 'name'] = "Winston Salem"
transit.at[14438, 'name'] = "Lexington"
transit.at[26404, 'name'] = "Indianapolis"
transit.at[1232, 'name'] = "Mt. Pleasant"
transit.at[9719, 'name'] = "Redondo Bch."
transit.at[9279, 'name'] = "Montrose"
transit.at[9896, 'name'] = "S. Pasadena"

In [8]:
df.head()

,store_name,street,city,state,zip,final_zip_pred,Population,Zip,County,AverageMbps,FastestAverageMbps
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,0.047050,54293.0,94087,Santa Clara,101.59,243.35
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,0.069219,49046.0,92656,Orange,116.61,297.85
2,Trader Joe's Brookline (501),1317 Beacon St,Brookline,MA,02446,0.032207,29311.0,02446,Norfolk,113.27,268.97
3,Trader Joe's Park Ridge (698),190 N NW Highway,Park Ridge,IL,60068,0.070867,37475.0,60068,Cook,147.68,295.55
4,Trader Joe's Scottsdale (94),6202 N Scottsdale Rd,Scottsdale,AZ,85253,0.148078,17047.0,85253,Maricopa,156.16,336.65

In [9]:
df_all = pd.merge(df, transit, how='left', left_on=['city', 'state'], right_on=['name', 'state'])
print(df_all.shape)
df_all.head()

(527, 17)

,store_name,street,city,state,zip,final_zip_pred,Population,Zip,County,AverageMbps,FastestAverageMbps,place,name,blkgrps,population,households,alltransit_performance_score
0,Trader Joe's Sunnyvale (68),316 West El Camino Real,Sunnyvale,CA,94087,0.047050,54293.0,94087,Santa Clara,101.59,243.35,677000.0,Sunnyvale,85.26,151957.23,55716.68,7.2
1,Trader Joe's Aliso Viejo (195),26541 Aliso Creek Rd,Aliso Viejo,CA,92656,0.069219,49046.0,92656,Orange,116.61,297.85,600947.0,Aliso Viejo,27.35,47087.10,17572.11,1.5
2,Trader Joe's Brookline (501),1317 Beacon St,Brookline,MA,02446,0.032207,29311.0,02446,Norfolk,113.27,268.97,2509210.0,Brookline,38.00,59246.00,24716.00,9.3
3,Trader Joe's Park Ridge (698),190 N NW Highway,Park Ridge,IL,60068,0.070867,37475.0,60068,Cook,147.68,295.55,1757875.0,Park Ridge,35.25,37990.57,14063.19,7.4
4,Trader Joe's Scottsdale (94),6202 N Scottsdale Rd,Scottsdale,AZ,85253,0.148078,17047.0,85253,Maricopa,156.16,336.65,465000.0,Scottsdale,162.94,234735.40,105858.04,5.1

In [10]:
df_all[df_all.alltransit_performance_score.isna()]

,store_name,street,city,state,zip,final_zip_pred,Population,Zip,County,AverageMbps,FastestAverageMbps,place,name,blkgrps,population,households,alltransit_performance_score
14,Trader Joe's Hanover (513),1775 Washington St,Hanover,MA,02339,0.087044,13879.0,02339,Plymouth,96.49,302.09,NaN,NaN,NaN,NaN,NaN,NaN
49,Trader Joe's Wayne (632),171 E Swedesford Rd,Wayne,PA,19087,0.068304,32225.0,19087,Chester,156.76,482.57,NaN,NaN,NaN,NaN,NaN,NaN
60,Trader Joe's Hyannis (514),655 Iyannough Road Rt 132,Hyannis,MA,02601,0.165784,14089.0,02601,Barnstable,99.95,273.05,NaN,NaN,NaN,NaN,NaN,NaN
62,Trader Joe's Studio City (122),11976 Ventura Blvd,Studio City,CA,91604,0.054496,29034.0,91604,Los Angeles,132.56,259.65,NaN,NaN,NaN,NaN,NaN,NaN
83,Trader Joe's Wayne (603),910 Hamburg Turnpike,Wayne,NJ,07470,0.076113,54717.0,07470,Passaic,80.32,219.07,NaN,NaN,NaN,NaN,NaN,NaN
91,Trader Joe's Long Island City (565),2243 Jackson Ave,Long Island City,NY,11101,0.073875,25484.0,11101,Queens,160.41,468.98,NaN,NaN,NaN,NaN,NaN,NaN
92,Trader Joe's Fairfield (523),2258 Black Rock Turnpike,Fairfield,CT,06825,0.049806,21123.0,06825,Fairfield,122.34,286.22,NaN,NaN,NaN,NaN,NaN,NaN
93,Trader Joe's West Newton (509),1121 Washington St,West Newton,MA,02465,0.032248,11710.0,02465,Middlesex,131.68,353.13,NaN,NaN,NaN,NaN,NaN,NaN
96,Trader Joe's Brooklyn (558),130 Court St,Brooklyn,NY,11201,0.057906,51128.0,11201,Kings,132.58,340.41,NaN,NaN,NaN,NaN,NaN,NaN
97,Trader Joe's Brooklyn - City Point (547),445 Gold St,Brooklyn,NY,11201,0.057906,51128.0,11201,Kings,132.58,340.41,NaN,NaN,NaN,NaN,NaN,NaN
122,Trader Joe's Sherman Oaks (49),14119 Riverside Dr,Sherman Oaks,CA,91423,0.045206,30991.0,91423,Los Angeles,113.02,291.73,NaN,NaN,NaN,NaN,NaN,NaN
124,Trader Joe's Acton (511),145 Great Rd,Acton,MA,01720,0.026176,21361.0,01720,Middlesex,131.20,348.20,NaN,NaN,NaN,NaN,NaN,NaN
134,Trader Joe's La Jolla (20),8657 Villa la Jolla Dr,La Jolla,CA,92037,0.061453,46781.0,92037,San Diego,125.37,257.52,NaN,NaN,NaN,NaN,NaN,NaN
164,Trader Joe's Staten Island (559),2385 Richmond Ave,Staten Island,NY,10314,0.088911,85510.0,10314,Richmond,112.51,301.45,NaN,NaN,NaN,NaN,NaN,NaN
168,Trader Joe's Larkspur (235),2052 Redwood Hwy,Greenbrae,CA,94904,0.045594,11995.0,94904,Marin,37.84,67.14,NaN,NaN,NaN,NaN,NaN,NaN
176,Trader Joe's North Hollywood (252),6130 Laurel Canyon Bl,North Hollywood,CA,91606,0.096240,44958.0,91606,Los Angeles,104.72,243.94,NaN,NaN,NaN,NaN,NaN,NaN
191,Trader Joe's Denville (617),3056 State Route 10 West,Denville,NJ,07834,0.057421,17722.0,07834,Morris,102.33,230.87,NaN,NaN,NaN,NaN,NaN,NaN
261,Trader Joe's North Brunswick (612),869 US-1,North Brunswick,NJ,08902,0.063829,41153.0,08902,Middlesex,85.56,211.74,NaN,NaN,NaN,NaN,NaN,NaN
264,Trader Joe's West Hills (50),6751 Fallbrook Ave,West Hills,CA,91307,0.090774,24474.0,91307,Los Angeles,127.96,295.50,NaN,NaN,NaN,NaN,NaN,NaN
268,Trader Joe's Encino (56),17640 Burbank Blvd,Encino,CA,91316,0.065590,26898.0,91316,Los Angeles,118.69,266.30,NaN,NaN,NaN,NaN,NaN,NaN
302,Trader Joe's Queens (557),9030 Metropolitan Ave,Rego Park,NY,11374,0.069992,43600.0,11374,Queens,106.81,233.74,NaN,NaN,NaN,NaN,NaN,NaN
310,Trader Joe's Brick (615),110 Brick Plaza,Brick,NJ,08723,0.138989,31641.0,08723,Ocean,105.04,259.51,NaN,NaN,NaN,NaN,NaN,NaN
322,Trader Joe's Millburn (609),187 Millburn Ave,Millburn,NJ,07041,0.025205,6868.0,07041,Essex,100.32,435.27,NaN,NaN,NaN,NaN,NaN,NaN
338,Trader Joe's Cherry Hill (613),775 Haddonfield Rd,Cherry Hill,NJ,08002,0.068457,22274.0,08002,Camden,96.89,233.83,NaN,NaN,NaN,NaN,NaN,NaN
350,Trader Joe's Granada Hills (44),11114 Balboa Blvd,Granada Hills,CA,91344,0.092939,51747.0,91344,Los Angeles,92.50,224.92,NaN,NaN,NaN,NaN,NaN,NaN
384,Trader Joe's Westchester (33),8645 S Sepulveda,Westchester,CA,90045,0.055647,39480.0,90045,Los Angeles,100.08,231.62,NaN,NaN,NaN,NaN,NaN,NaN
388,Trader Joe's Hadley (512),375 Russell St,Hadley,MA,01035,0.056507,5250.0,01035,Hampshire,55.31,109.70,NaN,NaN,NaN,NaN,NaN,NaN
389,Trader Joe's La Canada (42),475 Foothill Blvd,La Canada,CA,91011,0.050271,20280.0,91011,Los Angeles,95.46,208.21,NaN,NaN,NaN,NaN,NaN,NaN
394,Trader Joe's Bedford (562),2 Market Street,Bedford,NH,03110,0.088392,21203.0,03110,Hillsborough,136.40,306.62,NaN,NaN,NaN,NaN,NaN,NaN
396,Trader Joe's Chatsworth (184),10330 Mason Ave,Chatsworth,CA,91311,0.115313,36557.0,91311,Los Angeles,92.87,227.72,NaN,NaN,NaN,NaN,NaN,NaN
407,Trader Joe's Woodland Hills (209),21055 Ventura Blvd,Woodland Hills,CA,91364,0.097583,25851.0,91364,Los Angeles,123.20,250.58,NaN,NaN,NaN,NaN,NaN,NaN
433,Trader Joe's Shrewsbury (508),77 Boston Turnpike,Shrewsbury,MA,01545,0.064644,35299.0,01545,Worcester,57.23,156.46,NaN,NaN,NaN,NaN,NaN,NaN
441,Trader Joe's Eagle Rock (55),1566 Colorado Blvd,Eagle Rock,CA,90041,0.066497,27425.0,90041,Los Angeles,79.45,221.87,NaN,NaN,NaN,NaN,NaN,NaN
455,Trader Joe's Bridgewater (614),315 Promenade Blvd,Bridgewater,NJ,08807,0.078412,37972.0,08807,Somerset,127.39,335.17,NaN,NaN,NaN,NaN,NaN,NaN
456,Trader Joe's Marina Del Rey (205),4675 Admiralty Way,Marina Del Rey,CA,90292,0.063299,21576.0,90292,Los Angeles,127.04,275.03,NaN,NaN,NaN,NaN,NaN,NaN
484,Trader Joe's Toluca Lake (54),10130 Riverside Dr,Toluca Lake,CA,91602,0.061976,17473.0,91602,Los Angeles,102.94,229.28,NaN,NaN,NaN,NaN,NaN,NaN
494,Trader Joe's Allston (561),199 North Harvard Street,Allston,MA,02134,0.059133,21503.0,02134,Suffolk,101.06,262.37,NaN,NaN,NaN,NaN,NaN,NaN
522,Trader Joe's Clackamas (152),9345 SE 82nd Ave,Clackamas,OR,97086,0.146754,26010.0,97086,Clackamas,99.54,256.50,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_all.at[20, 'alltransit_performance_score'] = 8.2
df_all.at[43, 'alltransit_performance_score'] = 8.0 
df_all.at[50, 'alltransit_performance_score'] = 3.3  
df_all.at[59, 'alltransit_performance_score'] = 4.9  
df_all.at[61, 'alltransit_performance_score'] = 7.6 
df_all.at[96, 'alltransit_performance_score'] = 3.9
df_all.at[99, 'alltransit_performance_score'] = 0.7
df_all.at[126, 'alltransit_performance_score'] = 5.4 
df_all.at[136, 'alltransit_performance_score'] = 8.7 
df_all.at[137, 'alltransit_performance_score'] = 3.8
df_all.at[140, 'alltransit_performance_score'] = 8.0 
df_all.at[144, 'alltransit_performance_score'] = 4.4 
df_all.at[157, 'alltransit_performance_score'] = 8.1 
df_all.at[160, 'alltransit_performance_score'] = 6.9
df_all.at[172, 'alltransit_performance_score'] = 8.1 
df_all.at[189, 'alltransit_performance_score'] = 0.0 
df_all.at[192, 'alltransit_performance_score'] = 6.3  
df_all.at[193, 'alltransit_performance_score'] = 7.8  
df_all.at[196, 'alltransit_performance_score'] = 1.0
df_all.at[203, 'alltransit_performance_score'] = 3.5
df_all.at[205, 'alltransit_performance_score'] = 1.7
df_all.at[206, 'alltransit_performance_score'] = 9.6
df_all.at[290, 'alltransit_performance_score'] = 6.7 
df_all.at[331, 'alltransit_performance_score'] = 4.1 
df_all.at[348, 'alltransit_performance_score'] = 6.2 
df_all.at[407, 'alltransit_performance_score'] = 0.4 
df_all.at[419, 'alltransit_performance_score'] = 4.4 
df_all.at[422, 'alltransit_performance_score'] = 3.4 
df_all.at[425, 'alltransit_performance_score'] = 3.5
df_all.at[426, 'alltransit_performance_score'] = 1.4
df_all.at[427, 'alltransit_performance_score'] = 6.4
df_all.at[429, 'alltransit_performance_score'] = 6.2
df_all.at[433, 'alltransit_performance_score'] = 1.8

# Drop duplicate cities and states

In [12]:
keep = ['city', 'state', 'zip', 'final_zip_pred', 'AverageMbps', 'alltransit_performance_score']
one_city = df_all.loc[:, keep].drop_duplicates(subset=['city', 'state'])
one_city.shape

(415, 6)

In [13]:
one_city.sort_values(by=['alltransit_performance_score','AverageMbps'], ascending=False)[:10]

,city,state,zip,final_zip_pred,AverageMbps,alltransit_performance_score
36,New York,NY,10025,0.056589,139.28,9.6
64,San Francisco,CA,94103,0.065042,124.52,9.6
206,Clifton,NJ,07012,0.065477,70.00,9.6
329,Hoboken,NJ,07030,0.050021,113.79,9.5
2,Brookline,MA,02446,0.032207,113.27,9.3
236,Boston,MA,02210,0.063651,93.98,9.3
95,Washington,DC,20037,0.042724,70.48,9.3
7,Chicago,IL,60613,0.040591,118.29,9.1
110,Cambridge,MA,02139,0.027094,87.75,9.1
180,Oak Park,IL,60301,0.052411,14.13,9.1

In [14]:
one_city.head()

,city,state,zip,final_zip_pred,AverageMbps,alltransit_performance_score
0,Sunnyvale,CA,94087,0.047050,101.59,7.2
1,Aliso Viejo,CA,92656,0.069219,116.61,1.5
2,Brookline,MA,02446,0.032207,113.27,9.3
3,Park Ridge,IL,60068,0.070867,147.68,7.4
4,Scottsdale,AZ,85253,0.148078,156.16,5.1

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,10))

original = ['final_zip_pred', 'AverageMbps']

In [18]:
one_city[original] = scaler.fit_transform(one_city[original])
one_city[original] = one_city[original].round(1)

In [19]:
one_city

,city,state,zip,final_zip_pred,AverageMbps,alltransit_performance_score
0,Sunnyvale,CA,94087,1.1,3.6,7.2
1,Aliso Viejo,CA,92656,1.8,4.2,1.5
2,Brookline,MA,02446,0.6,4.1,9.3
3,Park Ridge,IL,60068,1.8,5.5,7.4
4,Scottsdale,AZ,85253,4.2,5.8,5.1
...,...,...,...,...,...,...
521,Livermore,CA,94550,2.3,3.7,4.3
522,Clackamas,OR,97086,4.1,3.5,NaN
523,Arlington,VA,22201,0.6,5.2,8.9
524,Florham Park,NJ,07932,1.6,4.1,3.7
526,Towson,MD,21204,1.1,6.7,6.4

In [21]:
print(one_city.shape)
one_city.head()

(415, 6)

,city,state,zip,final_zip_pred,AverageMbps,alltransit_performance_score
0,Sunnyvale,CA,94087,1.1,3.6,7.2
1,Aliso Viejo,CA,92656,1.8,4.2,1.5
2,Brookline,MA,02446,0.6,4.1,9.3
3,Park Ridge,IL,60068,1.8,5.5,7.4
4,Scottsdale,AZ,85253,4.2,5.8,5.1

In [22]:
one_city['total'] = (one_city["alltransit_performance_score"] + one_city['AverageMbps']) - one_city['final_zip_pred']

In [23]:
one_city.loc[:, 'total'] = one_city.loc[:, 'total'].round(2)
one_city.sort_values(by='total', ascending=False)[:20]

,city,state,zip,final_zip_pred,AverageMbps,alltransit_performance_score,total
423,Edgewater,NJ,07020,1.6,6.7,8.5,13.6
277,Reston,VA,20194,0.6,6.9,7.3,13.6
523,Arlington,VA,22201,0.6,5.2,8.9,13.5
36,New York,NY,10025,1.4,5.1,9.6,13.3
38,Bethesda,MD,20815,0.1,5.1,8.0,13.0
294,Silver Spring,MD,20901,0.7,4.6,9.0,12.9
33,Larchmont,NY,10538,0.8,5.1,8.6,12.9
2,Brookline,MA,02446,0.6,4.1,9.3,12.8
148,Alexandria,VA,22314,0.8,4.7,8.6,12.5
7,Chicago,IL,60613,0.9,4.3,9.1,12.5
64,San Francisco,CA,94103,1.6,4.5,9.6,12.5
477,Rockville,MD,20852,0.6,4.5,8.5,12.4
329,Hoboken,NJ,07030,1.2,4.1,9.5,12.4
372,Scarsdale,NY,10583,0.5,5.5,7.4,12.4
44,Arlington,MA,02476,0.4,4.4,8.2,12.2
165,Los Angeles,CA,90089,0.0,4.5,7.7,12.2
503,Chula Vista,CA,91914,3.6,10.0,5.7,12.1
249,Santa Monica,CA,90403,1.5,4.9,8.6,12.0
114,Brentwood,MO,63144,0.8,4.9,7.9,12.0
526,Towson,MD,21204,1.1,6.7,6.4,12.0

In [24]:
columns = ['country code', 'zip', 'place_name', 'state', 'state_abr',
           'county_1', 'county_2', 'com_1', 'com_2', 'lat', 'long', 'accur']

In [25]:
lat_long = pd.read_csv('data/00.raw/US/US.txt', 
                        sep='\t', 
                        names=columns, 
                        dtype={'zip':object},
                        usecols=['zip', 'lat', 'long', 'place_name'])
lat_long.head()

     zip  place_name      lat      long
0  99553      Akutan  54.1430 -165.7854
1  99571    Cold Bay  55.1858 -162.7211
2  99583  False Pass  54.8542 -163.4113
3  99612   King Cove  55.0628 -162.3056
4  99661  Sand Point  55.3192 -160.4914

In [26]:
cities_lat_long = pd.merge(one_city, lat_long, how='left', left_on='zip', right_on='zip')

cities_lat_long.head(10)

,city,state,zip,final_zip_pred,AverageMbps,alltransit_performance_score,total,place_name,lat,long
0,Sunnyvale,CA,94087,1.1,3.6,7.2,9.7,Sunnyvale,37.3502,-122.0349
1,Aliso Viejo,CA,92656,1.8,4.2,1.5,3.9,Aliso Viejo,33.5701,-117.7086
2,Brookline,MA,02446,0.6,4.1,9.3,12.8,Brookline,42.3431,-71.1230
3,Park Ridge,IL,60068,1.8,5.5,7.4,11.1,Park Ridge,42.0122,-87.8417
4,Scottsdale,AZ,85253,4.2,5.8,5.1,6.7,Paradise Valley,33.5494,-111.9565
5,Annapolis,MD,21401,3.5,5.0,5.8,7.3,Annapolis,38.9898,-76.5501
6,San Antonio,TX,78209,2.8,5.2,6.6,9.0,San Antonio,29.4821,-98.4554
7,Chicago,IL,60613,0.9,4.3,9.1,12.5,Chicago,41.9543,-87.6575
8,Queen Creek,AZ,85142,10.0,4.4,0.0,-5.6,Queen Creek,33.2487,-111.6343
9,Newport Beach,CA,92657,1.7,3.3,3.9,5.5,Newport Coast,33.5943,-117.8334

In [30]:
cities_lat_long[cities_lat_long["state"]=="NC"].sort_values(by="total", ascending=False)[:20]

,city,state,zip,final_zip_pred,AverageMbps,alltransit_performance_score,total,place_name,lat,long
154,Chapel Hill,NC,27514,1.1,4.3,6.1,9.3,Chapel Hill,35.9203,-79.0372
59,Wilmington,NC,28403,3.4,4.2,7.6,8.4,Wilmington,34.2237,-77.8862
181,Charlotte,NC,28204,1.3,3.2,5.0,6.9,Charlotte,35.2132,-80.8231
197,Raleigh,NC,27609,2.0,3.2,4.9,6.1,Raleigh,35.8480,-78.6317
407,Cary,NC,27511,1.7,4.3,3.0,5.6,Cary,35.7641,-78.7786
32,Asheville,NC,28801,2.8,3.1,4.3,4.6,Asheville,35.5971,-82.5565
161,Greensboro,NC,27410,2.6,3.1,3.7,4.2,Greensboro,36.1032,-79.8794
105,Winston Salem,NC,27103,6.1,3.5,3.4,0.8,Winston-Salem,36.0671,-80.3025