In [1]:
from constants import STORE_COLUMNS, INTERNET_SPEED_COLUMNS, INTERNET_SPEED_INT_COLUMNS, STORES_TABLE, INTERNET_SPEED_TABLE, PUBLIC_TRANSIT_COLUMNS, PUBLIC_TRANSIT_TABLE
from create_tables import create_tables 
from get_data.get_trader_joes import create_dataframe, write_store_urls_to_csv 
from upsert_data import upsert_dataframe_batch
from insert_data import insert_df


from get_data.get_public_transit import get_public_transit_data

import pandas as pd

In [2]:
df = get_public_transit_data()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29324 entries, 0 to 29323
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   place                         29324 non-null  str
 1   name                          29324 non-null  str
 2   blkgrps                       29324 non-null  float64
 3   population                    29324 non-null  float64
 4   households                    29324 non-null  float64
 5   alltransit_performance_score  29322 non-null  float64
dtypes: float64(4), str(2)
memory usage: 1.3 MB

In [3]:
df.head()

,place,name,blkgrps,population,households,alltransit_performance_score
0,4200100,Aaronsburg,0.02,22.92,8.48,0.0
1,4200104,Aaronsburg,0.79,502.31,209.62,0.0
2,4200116,Abbottstown,0.20,276.04,96.74,0.0
3,4200244,Ackermanville,0.24,571.42,198.55,0.1
4,4200332,Adamsburg,0.09,158.51,64.71,2.7

In [4]:
df[df['name']=='Hyder']

,place,name,blkgrps,population,households,alltransit_performance_score
19689,0234570,Hyder,0.09,0.0,0.0,NaN

In [5]:
command = open('sql/create_public_transit.sql', "r").read()
create_tables(command)

Connected to the PostgreSQL server.
Schema 'raw' created or already exists.
Table created successfully.
Database connection closed.

In [6]:
insert_df(df=df, table_name=PUBLIC_TRANSIT_TABLE, columns=PUBLIC_TRANSIT_COLUMNS)

✅ 29324 rows inserted in <1 second!

In [3]:
# urls = write_store_urls_to_csv()

In [4]:
# df = create_dataframe()

In [5]:
df = pd.read_csv('./data/stores.csv') 

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 647 entries, 0 to 646
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_number  647 non-null    int64
 1   store_name    647 non-null    str
 2   street        647 non-null    str
 3   city          647 non-null    str
 4   state         647 non-null    str
 5   zip_code      647 non-null    int64
 6   phone_number  647 non-null    str
 7   url           647 non-null    str
dtypes: int64(2), str(6)
memory usage: 40.6 KB

### Add the data

In [ ]:
# upsert_dataframe_batch(df=df, table_name="stores", conflict_column="url", columns=STORE_COLUMNS)




# insert_df(df=df, table_name=STORES_TABLE, columns=STORE_COLUMNS)

✅ 647 rows inserted in <1 second!

## Add data to the Internet Speed Table

In [7]:
from get_data.get_internet_speeds import get_internet_speeds_df

df = get_internet_speeds_df()

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32608 entries, 0 to 32607
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   zip                                  32608 non-null  str
 1   population                           29727 non-null  Int64
 2   county                               32608 non-null  str
 3   state                                32608 non-null  str
 4   wiredcount_2020                      29733 non-null  Int64
 5   fwcount_2020                         29733 non-null  Int64
 6   allprovidercount_2020                29733 non-null  Int64
 7   wired25_3_2020                       29733 non-null  Int64
 8   wired100_3_2020                      29733 non-null  Int64
 9   all25_3_2020                         29733 non-null  Int64
 10  all100_3_2020                        29733 non-null  Int64
 11  testcount                            26368 non-null  Int64
 12  averagembps                          26368 non-null  float64
 13  fastestaveragembps                   26368 non-null  float64
 14  access_terrestrial_broadband         29685 non-null  str
 15  lowest_priced_terrestrial_broadband  26630 non-null  float64
 16  wiredcount_2015                      29730 non-null  Int64
 17  fwcount_2015                         29730 non-null  Int64
 18  allprovidercount_2015                29730 non-null  Int64
 19  wired25_3_2015                       29730 non-null  Int64
 20  wired100_3_2015                      29730 non-null  Int64
 21  all25_3_2015                         29730 non-null  Int64
 22  all100_3_1                           29730 non-null  Int64
dtypes: Int64(16), float64(3), str(4)
memory usage: 6.2 MB

In [10]:
insert_df(df=df, table_name=INTERNET_SPEED_TABLE, columns=INTERNET_SPEED_COLUMNS)

✅ 32608 rows inserted in <1 second!

In [5]:
df.columns

Index(['zip', 'population', 'county', 'state', 'wiredcount_2020',
       'fwcount_2020', 'allprovidercount_2020', 'wired25_3_2020',
       'wired100_3_2020', 'all25_3_2020', 'all100_3_2020', 'testcount',
       'averagembps', 'fastestaveragembps', 'access_terrestrial_broadband',
       'lowest_priced_terrestrial_broadband', 'wiredcount_2015',
       'fwcount_2015', 'allprovidercount_2015', 'wired25_3_2015',
       'wired100_3_2015', 'all25_3_2015', 'all100_3_1'],
      dtype='str')

In [8]:
assert df.columns.tolist() == INTERNET_SPEED_COLUMNS