In [1]:
import pandas as pd
import glob
import os

In [2]:
joined_files = os.path.join('data/00.raw/transit', "*.csv")
joined_files

'data/00.raw/transit/*.csv'

In [3]:
# A list of all joined files is returned
joined_list = glob.glob(joined_files)

In [4]:
# Finally, the files are joined
df = pd.concat(map(pd.read_csv, joined_list), ignore_index=True)
# df = df.replace('"', '', regex=True)
df.head()

,place,name,blkgrps,population,households,alltransit_performance_score
0,"""2800100""","""Abbeville""",0.15,201.66,86.09,0.0
1,"""2800180""","""Aberdeen""",4.92,4308.42,1713.54,0.0
2,"""2800300""","""Ackerman""",1.02,712.88,306.24,0.0
3,"""2800680""","""Alcorn State University""",0.17,193.22,30.41,0.0
4,"""2800820""","""Algoma""",0.15,290.44,103.73,0.0

In [5]:
states = ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", 
          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", 
          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", 
          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", 
          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]

In [6]:
len(states)

51

In [7]:
len(joined_list)

51

In [8]:
joined_list.sort()

In [9]:
state_dict = dict(zip(joined_list, states))

In [10]:
for k, v in state_dict.items():
    df = pd.read_csv(k)
    df['state'] = v
    df.to_csv('data/01.transformed/transit/'+str(v)+'.csv', index=False)

In [11]:
state_files = os.path.join('data/01.transformed/transit', "*.csv")
joined_states = glob.glob(state_files)

In [12]:
df_states = pd.concat(map(pd.read_csv, joined_states))
df_states = df_states.replace('"', '', regex=True)
df_states.head()

,place,name,blkgrps,population,households,alltransit_performance_score,state
0,1600100,Aberdeen,1.03,1364.42,426.26,0.0,ID
1,1600280,Acequia,0.01,17.81,6.47,0.0,ID
2,1601000,Albion,0.00,1.45,0.48,0.0,ID
3,1601900,American Falls,1.71,2393.44,779.77,0.0,ID
4,1601990,Ammon,3.64,11207.42,3730.59,0.9,ID

In [13]:
df_states.to_csv('data/01.transformed/transit.csv', index=False)